config:
  onlyconsole: "false"
  logger: "true" #make a file with a list of ip who tried to enter with an account
  permission: "tsecurity.alert" ##Player who has this permission would see and alert when a player failed to join with an account
  ban_after: "5"   #number of Attempts before the user will be blocked.
  ban_command: "tsecurity ban %ip%"  #put your ban command that is gonna be executed when a user failed to login with an account after the number of attempts.
  players:  ##list of players.
    - "player"
  accounts-ip:
    player:
      - "1.27.0.01"
  banned_ips:
    - "12.12.12.12"
